name: ChangelogUI
author: Ameer4Real
main: Ameer4Real\ChangelogUI
version: 1.0
description: UI
api: [3.0.0]
commands:
    changelog:
        default: true
        atlas: [cl]
        description: See whats new on the server!
